spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine
    username: root
    password: TestPass85&64
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        useConfigs: maxPerformance
        rewriteBatchedStatements: true
  liquibase:
    change-log: db/master.xml
#    drop-first: true

server:
  servlet:
    contextPath: /

available-sites-list:
  sites:
    - url: http://www.playback.ru
      name: Интернет-магазин playback.ru
    - url: https://www.svetlovka.ru
      name: Библиотека Светловка

search-bot-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
referrer: http://www.google.com